config/routes.rb
Rails.application.routes.draw do
  resources :kittens

  root "kittens#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/kitten.rb
class Kitten < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  def index
    @kittens = Kitten.all

    respond_to do |format|
      format.html

      format.json {render :json => @kittens}
    end
  end

  def show
    @kitten = Kitten.find(params[:id])

    respond_to do |format|
      format.html

      format.json {render :json => @kitten}
    end
  end

  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(kitten_params)

    if @kitten.save
      flash[:success] = 'Kitten was created!!'
      redirect_to @kitten, notice: "Kitten succesfully created."
    else
      flash[:alert] = 'Error creating kitten. You suck.'
      render :new
    end
  end

  def edit
    @kitten = Kitten.find(params[:id])																																									
  end

  def update
    @kitten = Kitten.find(params[:id])

    if @kitten.update(kitten_params)
      flash[:success] = 'Kitten updated the cat!!'
      redirect_to @kitten, notice: "Kitten successfully updated"
    else
      flash[:alert] = 'You need a new Job. Redo the form. '
      render :edit
    end
  end

  def destroy
    @kitten = Kitten.find(params[:id])
    @kitten.destroy
    flash[:success] = 'Kitten was burned alive!!'
    redirect_to kittens_path
  end

  private

  def kitten_params
    params.require(:kitten).permit(:name, :age, :cuteness, :softness)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<%= form_with(model: @kitten, local: true) do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div>
    <%= form.label :cuteness %>
    <%= form.number_field :cuteness %>
  </div>

  <div>
    <%= form.label :softness %>
    <%= form.number_field :softness %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/kittens/create.html.erb
<h1>Kittens#create</h1>
<p>Find me in app/views/kittens/create.html.erb</p>

app/views/kittens/destroy.html.erb
<h1>Kittens#destroy</h1>
<p>Find me in app/views/kittens/destroy.html.erb</p>

app/views/kittens/edit.html.erb
<h1>Edit Kitten</h1>

<%= render 'form' %>

<%= link_to 'Delete Kitten', kitten_path(@kitten), method: :delete, data: { confirm: 'Are you sure?' } %>
<%= link_to 'Back', kittens_path %>

app/views/kittens/index.html.erb
<h1>All Kittens</h1>

<ul>
    <% @kittens.each do |kitten| %>
        <div>
            <li><%= kitten.name %></li>
            <li><%= kitten.age %></li>
            <li><%= kitten.cuteness %></li>
            <li><%= kitten.softness %></li>
            <%= link_to 'Delete Kitten', kitten_path(kitten), method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
    <% end %>
</ul>

<%= link_to "Create Kitten", new_kitten_path(@kitten) %>

app/views/kittens/new.html.erb
<h1>New Kitten</h1>

<%= render 'form' %>

<%= link_to 'Back', kittens_path %>

app/views/kittens/show.html.erb
<h1>Kitten Details</h1>

<div>
    <p><strong>Name:</strong> <%= @kitten.name %></p>
    <p><strong>Age:</strong> <%= @kitten.age %></p>
    <p><strong>Cuteness:</strong> <%= @kitten.cuteness %></p>
    <p><strong>Softness:</strong> <%= @kitten.softness %></p>
</div>

<%# <%= button_to 'Delete Kitten', kitten_path(@kitten), method: :delete, data: { confirm: 'Are you sure?' } %> 
<%= link_to 'Delete Kitten', kitten_path(@kitten), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'} %>

<%= link_to 'Edit', edit_kitten_path(@kitten) %>
<%= link_to 'Back', kittens_path %>

app/views/kittens/update.html.erb
<h1>Kittens#update</h1>
<p>Find me in app/views/kittens/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <% flash.each do |key, message| %>
      <div class="flash" <%= key%>>
        <%= message %>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>